// Generated by https://quicktype.io
export interface CostoProducto {
  id_producto: number;
  unidad: string;
  Moneda: string;
  precio: number;
}

export interface Medidas {
  ancho: number;
  alto: number;
}
